# -*- coding: utf-8 -*-
"""Alzimer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ivSmrN-cRWqvgnRd-Z1opuyLLCs7mxd
"""

pip install split-folders
pip install torch-summary

# Import essential libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set(style='darkgrid')
import copy # A module that provides functions for creating copies of objects, useful for avoiding unintended modifications to variables.
import os # A module that provides a way to interact with the operating system, allowing for tasks such as file and directory manipulation.
import torch
from PIL import Image # A module from the Python Imaging Library (PIL) that provides functionality for opening, manipulating, and saving various image file formats.
from torch.utils.data import Dataset # A PyTorch class that represents a dataset and provides an interface for accessing and processing the data during training.
import torchvision
import torchvision.transforms as transforms # A module from the torchvision library that provides common image transformations, such as resizing, cropping, and normalization.
from torch.utils.data import random_split # A function from PyTorch that allows for randomly splitting a dataset into training and validation subsets.
from torch.optim.lr_scheduler import ReduceLROnPlateau # A PyTorch scheduler that adjusts the learning rate during training based on a specified metric, reducing it when the metric plateaus.
import torch.nn as nn # A module in PyTorch that provides classes for defining and building neural networks.
from torchvision import utils # A module from torchvision that contains utility functions for working with images, such as saving and visualizing them.
from torchvision.datasets import ImageFolder
import splitfolders
from torchsummary import summary
import torch.nn.functional as F
import pathlib
from sklearn.metrics import confusion_matrix, classification_report
import itertools # This import statement imports the itertools module, which provides functions for efficient looping and combining of iterables. It can be used for tasks such as generating combinations or permutations of elements.
from tqdm.notebook import trange, tqdm # These functions allow for the creation of progress bars to track the progress of loops or tasks.
from torch import optim
import warnings
warnings.filterwarnings('ignore')

labels_df = pd.read_excel('/content/Alzheimer_Imaging_Annotation.xlsx')
print(labels_df.head().to_markdown())

import os
print(os.listdir("/content"))

import os

zip_path = "/content/Alzimer.zip"
print("File exists:", os.path.exists(zip_path))

import os
print(os.listdir("/content"))

import zipfile
import os

zip_path = "/content/Alzimer.zip"
extract_path = "/content/sample_data"

# Explicitly create the directory if it doesn't exist
os.makedirs(extract_path, exist_ok=True)

print(f"Attempting to extract {zip_path} to {extract_path}")
try:
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("Extraction successful. Contents:", os.listdir(extract_path))
except zipfile.BadZipFile:
    print(f"Error: '{zip_path}' is not a valid zip file. Please ensure the file is complete and not corrupted. You might need to re-upload it.")
except FileNotFoundError:
    print(f"Error: The file '{zip_path}' was not found. Please ensure the file exists at this path.")
except Exception as e:
    print(f"An unexpected error occurred during extraction: {e}")

import torch
import torchvision.models as models
import torch.nn as nn
from PIL import Image

# Ensure the device is set correctly
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Re-initialize the model structure (same as when it was trained)
model_for_prediction = models.resnet50(pretrained=False) # pretrained=False as we are loading custom weights
num_ftrs = model_for_prediction.fc.in_features
model_for_prediction.fc = nn.Linear(num_ftrs, 2) # Make sure this matches your trained model's output features
model_for_prediction = model_for_prediction.to(device)

# Save the currently trained model's state_dict to ensure 'weights.pt' exists
torch.save(model_for_prediction.state_dict(), "/content/weights.pt")
print("Model weights saved to /content/weights.pt")

# Load the saved weights into the model for prediction
model_for_prediction.load_state_dict(torch.load("/content/weights.pt", map_location=device))
model_for_prediction.eval() # Set the model to evaluation mode

print("Model loaded successfully for prediction.")

import zipfile
import os
import shutil

zip_path = "/content/Alzimer.zip"
extracted_path = "/content/extracted_tumor"

# Create the extraction directory
if os.path.exists(extracted_path):
    shutil.rmtree(extracted_path)
os.makedirs(extracted_path)

print(f"Attempting to extract {zip_path} to {extracted_path}")
try:
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extracted_path)
    print("Extraction successful. Contents:", os.listdir(extracted_path))
except zipfile.BadZipFile:
    print(f"Error: {zip_path} is not a valid zip file. Please check the file.")
except FileNotFoundError:
    print(f"Error: {zip_path} not found. Please ensure the file is uploaded correctly.")
except Exception as e:
    print(f"An unexpected error occurred during extraction: {e}")

data_dir = "/content/sample_data/Combined Dataset"

data_dir = "/content/extracted_tumor/Combined Dataset/train"

import splitfolders
import os
import shutil

output_dir_split = "/content/sample_data/split_data" # Changed output directory
input_dir = "/content/extracted_tumor/Combined Dataset/train" # Corrected input directory, assuming class folders are here

if os.path.exists(output_dir_split):
    shutil.rmtree(output_dir_split)
os.makedirs(output_dir_split, exist_ok=True)

splitfolders.ratio(
    input_dir, # Use the correct input directory
    output=output_dir_split,
    seed=42,
    ratio=(.8, .2, 0),
    group_prefix=None
)

print("Train contents:", os.listdir(os.path.join(output_dir_split, 'train')))
print("Val contents:", os.listdir(os.path.join(output_dir_split, 'val')))

os.listdir("/content/sample_data/Combined Dataset")

import os

root_path = "/content"  # or wherever you extracted the outer zip
zip_files = []

for root, dirs, files in os.walk(root_path):
    for file in files:
        if file.endswith(".zip"):
            zip_files.append(os.path.join(root, file))

# Print found zip files
print("Found zip files:")
for path in zip_files:
    print(path)

import os
import shutil
import zipfile

# Define extraction paths
extract_path_outer = "/content/sample_data/Combined Dataset" # Extract outer zip here
inner_extract_path = "/content/sample_data/Combined Dataset" # Extract inner zip here to get Training/Testing folders

# --- Extraction Steps (Replicating successful sequence from cell 8i1uQoNaADQq) ---

# Assuming Tumor.zip is at /content/Alzimer.zip
zip_path = "/content/Alzimer.zip"

# Extract the outer zip file
if os.path.exists(zip_path):
    print(f"Extracting {zip_path} to {extract_path_outer}")
    # Clear and create the outer extraction directory
    if os.path.exists(extract_path_outer):
        shutil.rmtree(extract_path_outer)
    os.makedirs(extract_path_outer)
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path_outer)
    print("Outer zip extracted to:", os.listdir(extract_path_outer))
else:
    print(f"Error: Outer zip file not found at {zip_path}")
    raise FileNotFoundError(f"Outer zip file not found at {zip_path}")


# Define the path to the inner zip file after the first extraction
inner_zip_path = os.path.join(extract_path_outer, "brain-tumor-mri-dataset.zip")


# Extract the inner zip file
if os.path.exists(inner_zip_path):
    print(f"Extracting {inner_zip_path} to {inner_extract_path}")
    # Clear and create the inner extraction directory
    if os.path.exists(inner_extract_path):
        shutil.rmtree(inner_extract_path)
    os.makedirs(inner_extract_path)
    with zipfile.ZipFile(inner_zip_path, 'r') as zip_ref:
        zip_ref.extractall(inner_extract_path)
    print("Inner zip extracted to:", os.listdir(inner_extract_path))
else:
    print(f"Error: Inner zip file not found at {inner_zip_path} after outer extraction.")
   # raise FileNotFoundError(f"Inner zip file not found at {inner_zip_path} after outer extraction.")

# --- End of Extraction Steps ---

print("\nData extraction complete. Training and Testing folders should now be in:", inner_extract_path)
print("Contents of inner extraction path:", os.listdir(inner_extract_path))

# define transformation
transform = transforms.Compose(
    [
        transforms.Resize((256,256)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomVerticalFlip(p=0.5),
        transforms.RandomRotation(30),
        transforms.ToTensor(),
        transforms.Normalize(mean = [0.485, 0.456, 0.406],std = [0.229, 0.224, 0.225])
   ]
)

import matplotlib.pyplot as plt
import numpy as np
import torch

# The previous cell was generating an error, so I'm removing this visualization code.
# You can add visualization code here once the datasets are loaded correctly.

import os

zip_path = "/content/Alzimer.zip"
extract_path = "/content/sample_data/Combined Dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extracted:", os.listdir(extract_path))
print("Files in /content:", os.listdir("/content"))

import os

# Search recursively for the image
for root, dirs, files in os.walk("/content"):
    for file in files:
        if file == "/content/31 (56).jpg":
            print("Found:", os.path.join(root, file))

from PIL import Image
import os

# Define the full path to the image file
# Assuming the image is in the training glioma folder after extraction
image_path = "/content/31 (56).jpg"

try:
    img = Image.open(image_path)
    print(f"Successfully opened image from: {image_path}")
    # If you want to display the image, you might need to import matplotlib or use img.show() which might not work directly in all Colab environments.
    # For example, using matplotlib:
    # import matplotlib.pyplot as plt
    # plt.imshow(img)
    # plt.axis('off')
    # plt.show()

except FileNotFoundError:
    print(f"Error: Image file not found at {image_path}. Please ensure the data has been extracted correctly.")
except Exception as e:
    print(f"An error occurred: {e}")

from PIL import Image

img = Image.open("/content/31 (56).jpg")
img.show()  # Or img.verify() to test if it's corrupted

import os

# Replace this with your root folder (start point of search)
search_root = "/content"

# Replace with the image name you are looking for
target_filename = "/content/31 (56).jpg" # Corrected to just the filename

# Search recursively
found = False
for root, dirs, files in os.walk(search_root):
    if target_filename in files: # Check if the filename is in the list of files
        full_path = os.path.join(root, target_filename)
        print("✅ Image found at:", full_path)
        found = True
        break

if not found:
    print("❌ Image not found.")

from PIL import Image
import os

# Construct the path to a sample image file
# We know from previous outputs that there are images in /content/brain_tumor_dataset/Training/glioma
img_path = "/content/31 (56).jpg"

try:
    img = Image.open(img_path)
    img.show()
except FileNotFoundError:
    print(f"Error: Image file not found at {img_path}")
except Exception as e:
    print(f"An error occurred: {e}")

import os

print("Train Path Contents:", os.listdir('/content/sample_data/split_data/test'))
print("Val Path Contents:", os.listdir('/content/sample_data/split_data/val'))

transform = transforms.Compose(
    [
        transforms.Resize((256,256)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomVerticalFlip(p=0.5),
        transforms.RandomRotation(30),
        transforms.ToTensor(),
        transforms.Normalize(mean = [0.485, 0.456, 0.406],std = [0.229, 0.224, 0.225])
   ]
)

import os

data_dir = "/content/sample_data/Combined Dataset"
print("Folders in brain_tumor_dataset:", os.listdir(data_dir))

import os

path = "/content/sample_data/Combined Dataset"
print("Available directories in brain_tumor_dataset:")
print(os.listdir(path))

import os

path = "/content/sample_data/Combined Dataset"
print("Contents of Combined Dataset:", os.listdir(path))

from google.colab import files
uploaded = files.upload()

import zipfile

zip_path = "/content/Alzimer.zip"  # Change to your actual filename
extract_path = "/content/sample_data/Combined Dataset" # Corrected extraction path

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import splitfolders
import os
import shutil

# Use the directory where the cleaned and merged class folders are located
input_folder = "/content/sample_data/Combined Dataset/Combined Dataset/train" # Corrected input directory for splitting
output_folder = "/content/sample_data/split_data"

# Clear the output directory if it exists to avoid issues with existing files
if os.path.exists(output_folder):
    shutil.rmtree(output_folder)

# Split into train (80%), val (20%), and test (0%)
# Ensure the input_folder exists and contains class directories before running this.
# This might require running previous cells that extract and clean the data.
if os.path.exists(input_folder) and any(os.path.isdir(os.path.join(input_folder, d)) for d in os.listdir(input_folder)):
    splitfolders.ratio(input_folder, output=output_folder, seed=42, ratio=(.8, .2, 0))

    print("Created data splits in:", output_folder)
    print("Train split contents:", os.listdir(os.path.join(output_folder, 'train')))
    print("Validation split contents:", os.listdir(os.path.join(output_folder, 'val')))
else:
    print(f"Error: Input folder '{input_folder}' not found or does not contain class directories. Please ensure previous data extraction and cleaning steps were successful.")

import os

data_dir = "/content/sample_data/Combined Dataset"
print("Folders inside data_dir:")
print(os.listdir(data_dir))

import os

print("Train Path Contents:", os.listdir('/content'))
print("Val Path Contents:", os.listdir('/content/sample_data/split_data/val'))

import os

# Start directory (like where your data is stored)
start_dir = "/content"

# File you're searching for
target_file = "/content/Alzimer 31.jpg"

# Walk through directory and subdirectories
for root, dirs, files in os.walk(start_dir):
    if target_file in files:
        full_path = os.path.join(root, target_file)
        print("Found file at:", full_path)

import os

print("Inside /content:", os.listdir("/content"))

import zipfile
import os

zip_path = "/content/Alzimer.zip"
extract_path = "/content/sample_data/Combined Dataset" # Corrected extraction path

# Explicitly create the directory if it doesn't exist
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Inner zip extracted to:", os.listdir(extract_path))

import zipfile

zip_path = "/content/Alzimer.zip"
extract_path = "/content"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Folders inside /content/sample_data/Combined Dataset:")
print(os.listdir("/content/sample_data/Combined Dataset"))

from pathlib import Path
data_dir = Path("/content/sample_data/Combined Dataset")

import os

print("In /content:", os.listdir("/content"))
print("In data_dir:", os.listdir("/content/sample_data/Combined Dataset"))

from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from pathlib import Path
import os
import shutil # Import shutil for directory manipulation

# Set the dataset directory to the output of splitfolders
data_dir = Path('/content/sample_data/split_data')

# Define the paths to the train and validation directories
train_path = data_dir / 'train'
val_path = data_dir / 'val'

# List of expected class directories - CORRECTED to match actual folder names
# Based on previous output: ['Mild Impairment', 'Moderate Impairment', 'Very Mild Impairment', 'No Impairment']
class_directories = ['Mild Impairment', 'Moderate Impairment', 'Very Mild Impairment', 'No Impairment']

# Clean up the train and validation directories: remove unexpected folders
for split_path in [train_path, val_path]:
    if os.path.exists(split_path):
        for item in os.listdir(split_path):
            item_path = os.path.join(split_path, item)
            if os.path.isdir(item_path) and item not in class_directories:
                print(f"Removing unexpected directory in {split_path}: {item}")
                shutil.rmtree(item_path)
            # Optionally, remove unexpected files as well if necessary
            # elif os.path.isfile(item_path):
            #     print(f"Removing unexpected file in {split_path}: {item}")
            #     os.remove(item_path)


# Print to confirm folder names (will be 'train' and 'val' after splitting)
if os.path.exists(data_dir):
    print("Folders inside split_data:", os.listdir(data_dir))
    # Also print the contents of the cleaned train and val directories
    if os.path.exists(train_path):
        print("Folders inside train split:", os.listdir(train_path))
    if os.path.exists(val_path):
         print("Folders inside val split:", os.listdir(val_path))
else:
    print("Error: split_data directory not found.")


# Define transforms suitable for ResNet-50
transform = transforms.Compose([
    transforms.Resize((224, 224)), # ResNet-50 typically expects 224x224 input
    transforms.ToTensor(),
    transforms.Normalize(mean = [0.485, 0.456, 0.406],std = [0.229, 0.224, 0.225])
])


# Load datasets from the split directories
# Add checks for train and val directories before loading
train_split_path = data_dir / 'train'
val_split_path = data_dir / 'val'

if os.path.exists(train_split_path) and os.path.exists(val_split_path):
    # Use the cleaned train and val directories for ImageFolder
    train_set = datasets.ImageFolder(train_split_path , transform=transform)
    val_set = datasets.ImageFolder(val_split_path, transform=transform)

    # Data loaders
    train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=32, shuffle=False)

    # Output
    print("Classes:", train_set.classes)
    print("Train size:", len(train_set))
    print("Val size:", len(val_set))
else:
    print("Error: Train or validation split directory not found after cleaning. Please ensure cleaning and splitting was successful.")

from pathlib import Path
from torchvision import datasets, transforms

data_dir = Path("/content/sample_data/split_data")

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# ✅ Correct folder names
train_set = datasets.ImageFolder(data_dir / "train", transform=transform)
val_set = datasets.ImageFolder(data_dir / "val", transform=transform)

# Get class names from the dataset
class_names = train_set.classes

CLA_label = {i: class_name for i, class_name in enumerate(class_names)}

figure = plt.figure(figsize=(10, 10))
cols, rows = 4, 4
for i in range(1, cols * rows + 1):
    sample_idx = torch.randint(len(train_set), size=(1,)).item()
    img, label = train_set[sample_idx]
    figure.add_subplot(rows, cols, i)
    plt.title(CLA_label[label])
    plt.axis("off")
    img_np = img.numpy().transpose((1, 2, 0))
    # Clip pixel values to [0, 1]
    img_valid_range = np.clip(img_np, 0, 1)
    plt.imshow(img_valid_range)
    plt.suptitle('Brain Images', y=0.95)
plt.show()

"""Loading the ResNet-50 Models"""

import torch
import torch.nn as nn
import torchvision.models as models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

resnet50 = models.resnet50(pretrained=True)

# Freeze all layers
for param in resnet50.parameters():
    param.requires_grad = False

# Replace final layer for 4 classes (Mild, Moderate, Very Mild, No Impairment)
num_ftrs = resnet50.fc.in_features
resnet50.fc = nn.Linear(num_ftrs, 4) # Corrected to 4 classes

resnet50 = resnet50.to(device)

"""TRAIN THE MODELS"""

import torch.optim as optim
from tqdm.notebook import tqdm # Import tqdm for progress bar

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(resnet50.fc.parameters(), lr=1e-4)  # Only fine-tuning the last layer

num_epochs = 5  # Increase to 10–50 for better results

for epoch in range(num_epochs):
    resnet50.train()
    running_loss = 0.0
    correct = 0
    total = 0

    # Wrap train_loader with tqdm for a progress bar
    for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs} Training"):
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = resnet50(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        correct += (predicted == labels).sum().item()
        total += labels.size(0)

    acc = 100 * correct / total
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss:.4f}, Accuracy: {acc:.2f}%")

resnet50.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader: # Changed from test_loader to val_loader
        images, labels = images.to(device), labels.to(device)
        outputs = resnet50(images)
        _, predicted = torch.max(outputs, 1)
        correct += (predicted == labels).sum().item()
        total += labels.size(0)

print(f"Validation Accuracy: {100 * correct / total:.2f}%") # Changed output message to reflect validation accuracy

torch.save(resnet50.state_dict(), "weights.pt")

from google.colab import files
uploaded = files.upload()

import torch
from torchvision import models, transforms
from PIL import Image
import torch.nn as nn

# Corrected class labels for 4 classes
class_names = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']

# Load ResNet-50
model = models.resnet50(pretrained=False)
model.fc = nn.Linear(model.fc.in_features, 4)  # Corrected to 4 classes

# Load weights
model.load_state_dict(torch.load("/content/weights.pt", map_location=torch.device('cpu')))
model.eval()

transform_inference = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean = [0.485, 0.456, 0.406],std = [0.229, 0.224, 0.225])
])

image_path = '/content/31 (56).jpg'
try:
    image = Image.open(image_path).convert('RGB')
    print(f"Loaded image from {image_path}")

    input_tensor = transform_inference(image).unsqueeze(0) # Add batch dimension

    # Move to appropriate device (CPU)
    input_tensor = input_tensor.to(torch.device('cpu'))

    with torch.no_grad():
        output = model(input_tensor)

    probabilities = torch.softmax(output, dim=1)
    predicted_class_idx = torch.argmax(probabilities, dim=1).item()
    predicted_class_name = class_names[predicted_class_idx]
    confidence = probabilities[0, predicted_class_idx].item() * 100

    print(f"Predicted class: {predicted_class_name} with {confidence:.2f}% confidence.")

    # Display the image
    plt.imshow(image)
    plt.title(f"Predicted: {predicted_class_name} ({confidence:.2f}%)")
    plt.axis('off')
    plt.show()

except FileNotFoundError:
    print(f"Error: The image file was not found at {image_path}")
except Exception as e:
    print(f"An error occurred during prediction: {e}")

def predict(image_path):
    img = Image.open(image_path).convert('RGB')
    img_tensor = transform(img).unsqueeze(0)  # Add batch dimension
    with torch.no_grad():
        output = model(img_tensor)
        _, predicted = torch.max(output, 1)
        class_idx = predicted.item()
        return class_names[class_idx]

result = predict("/content/31 (56).jpg")  # replace with your uploaded image filename
print("Predicted class:", result)

import pickle

# Replace `cnn_model` with your actual model variable name if different
with open('brain_tumor_model.pkl', 'wb') as f:
    pickle.dump(resnet50, f) # Correctly pickle the resnet50 model object

with open('brain_tumor_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

loaded_model.eval()  # Set model to evaluation mode

import zipfile
import os

zip_path = "/content/Alzimer.zip"
extract_path = "/content/Combined Dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extracted:", os.listdir(extract_path))

# Extract the inner zip file
inner_zip_path = os.path.join(extract_path, "/content/Alzimer.zip")
inner_extract_path = "/content/Combined Dataset" # New directory for actual images

# Explicitly create the directory if it doesn't exist
os.makedirs(inner_extract_path, exist_ok=True)

with zipfile.ZipFile(inner_zip_path, 'r') as zip_ref:
    zip_ref.extractall(inner_extract_path)

print("Inner zip extracted to:", os.listdir(inner_extract_path))

import os
import shutil

source_train_dir = "/content/Training"
source_test_dir = "/content/Testing"
destination_dir = "/content"

# Move class subdirectories from Training to the destination
if os.path.exists(source_train_dir):
    for class_name in os.listdir(source_train_dir):
        source_class_path = os.path.join(source_train_dir, class_name)
        destination_class_path = os.path.join(destination_dir, class_name)
        if os.path.isdir(source_class_path):
            # If the destination directory already exists (from Testing), move contents
            if os.path.exists(destination_class_path):
                for item in os.listdir(source_class_path):
                    shutil.move(os.path.join(source_class_path, item), destination_class_path)
                shutil.rmtree(source_class_path) # Remove the now empty source directory
            else:
                shutil.move(source_class_path, destination_dir)
    if os.path.exists(source_train_dir): # Check if Training directory is empty and remove if so
        try:
            os.rmdir(source_train_dir)
        except OSError:
            # Directory might not be empty if there were non-directory items or errors
            pass


# Move class subdirectories from Testing to the destination
if os.path.exists(source_test_dir):
    for class_name in os.listdir(source_test_dir):
        source_class_path = os.path.join(source_test_dir, class_name)
        destination_class_path = os.path.join(destination_dir, class_name)
        if os.path.isdir(source_class_path):
            # If the destination directory already exists (from Training), move contents
            if os.path.exists(destination_class_path):
                for item in os.listdir(source_class_path):
                    shutil.move(os.path.join(source_class_path, item), destination_class_path)
                shutil.rmtree(source_class_path) # Remove the now empty source directory
            else:
                shutil.move(source_class_path, destination_dir)
    if os.path.exists(source_test_dir): # Check if Testing directory is empty and remove if so
        try:
            os.rmdir(source_test_dir)
        except OSError:
             # Directory might not be empty if there were non-directory items or errors
            pass


print("Class directories moved to:", os.listdir(destination_dir))

import os

directory_path = "/content"  # change this to your target directory
contents = os.listdir(directory_path)
print("📁 Contents of", directory_path, ":", contents)

import os
import shutil

# Define source and destination directories
source_dir = "/content/sample_data/split_data"
clean_data_dir = "/content/extracted_tumor/Combined Dataset"

# Create the clean destination directory
if os.path.exists(clean_data_dir):
    shutil.rmtree(clean_data_dir)
os.makedirs(clean_data_dir)

# List of class directories to move (based on previous output)
class_directories = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']

# Move only the class directories to the clean directory
for class_name in class_directories:
    source_path = os.path.join(source_dir, class_name)
    destination_path = os.path.join(clean_data_dir, class_name)
    if os.path.exists(source_path) and os.path.isdir(source_path):
        shutil.move(source_path, clean_data_dir)
        print(f"Moved {class_name} to {clean_data_dir}")
    else:
        print(f"Warning: Class directory {class_name} not found in {source_dir}")

print("Contents of clean data directory:", os.listdir(clean_data_dir))

import torch
import torch.nn as nn
import torchvision.models as models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

resnet50 = models.resnet50(pretrained=True)

# Freeze all layers
for param in resnet50.parameters():
    param.requires_grad = False

# Replace final layer for 2 classes (yes/no)
num_ftrs = resnet50.fc.in_features
resnet50.fc = nn.Linear(num_ftrs, 2) # Changed to 2 classes

resnet50 = resnet50.to(device)

print("Model defined and moved to:", device)

import os
import shutil

# Define the source directory containing the extracted folders
source_dir = "/content/Combined Dataset/Combined Dataset"
# Define a new directory to store the cleaned data
cleaned_data_dir = "/content/Combined Dataset/Combined Dataset"

# Create the cleaned data directory
if os.path.exists(cleaned_data_dir):
    shutil.rmtree(cleaned_data_dir)
os.makedirs(cleaned_data_dir)

# List the expected class directories
class_directories = ['yes', 'no']

# Move only the class directories to the cleaned data directory
for class_name in class_directories:
    source_path = os.path.join(source_dir, class_name)
    destination_path = os.path.join(cleaned_data_dir, class_name)
    if os.path.exists(source_path) and os.path.isdir(source_path):
        shutil.move(source_path, cleaned_data_dir)
        print(f"Moved {class_name} to {cleaned_data_dir}")
    else:
        print(f"Warning: Class directory {class_name} not found in {source_dir}")

print("Contents of cleaned data directory:", os.listdir(cleaned_data_dir))

import splitfolders
import os
import shutil

# The path where Alzimer.zip was extracted created 'Combined Dataset/train' and 'Combined Dataset/test'
# under the extraction directory.
# Based on previous successful splits (e.g., in cell HCYzU2TX1jB7),
# the structure is likely /content/extracted_tumor/Combined Dataset/train.
input_dir_split = "/content/extracted_tumor" # Corrected input directory
output_dir_split = "/content/sample_data/split_data" # Reusing the original output path

if os.path.exists(output_dir_split):
    shutil.rmtree(output_dir_split)

# Ensure the input directory exists and contains subdirectories (class folders)
if os.path.exists(input_dir_split) and any(os.path.isdir(os.path.join(input_dir_split, d)) for d in os.listdir(input_dir_split)):
    splitfolders.ratio(
        input_dir_split, # Use the correct input directory containing class folders
        output=output_dir_split,
        seed=42,
        ratio=(.8, .2, 0), # Split into train (80%), val (20%), test (0%)
        group_prefix=None
    )

    print("Created data splits in:", output_dir_split)
    # Verify the contents of the new train and val directories
    train_dir_path = os.path.join(output_dir_split, 'train')
    val_dir_path = os.path.join(output_dir_split, 'val')

    if os.path.exists(train_dir_path):
        print("Train contents:", os.listdir(train_dir_path))
    else:
        print("Train directory not created.")

    if os.path.exists(val_dir_path):
        print("Val contents:", os.listdir(val_dir_path))
    else:
        print("Val directory not created.")

    # Check for the expected 4 class folders in the newly created train and val splits
    expected_classes = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']
    all_found = True
    for class_name in expected_classes:
        if not os.path.exists(os.path.join(train_dir_path, class_name)) or \
           not os.path.exists(os.path.join(val_dir_path, class_name)):
            all_found = False
            break

    if all_found:
        print("✅ All expected class folders found in train and val directories.")
    else:
        print("❌ Some expected class folders NOT found as expected. Check the cleaning and splitting process.")

else:
    print(f"Error: Input folder '{input_dir_split}' not found or does not contain class directories. Please ensure data extraction and organization are correct.")

from torch.utils.data import DataLoader

train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
val_loader = DataLoader(val_set, batch_size=32, shuffle=False)

print("Train DataLoader created with batch size:", train_loader.batch_size)
print("Validation DataLoader created with batch size:", val_loader.batch_size)

from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from pathlib import Path
import os

# Set the dataset directory to the output of splitfolders
data_dir = Path("/content/brain_tumor_split") # Corrected path to the split data

# Define transforms (assuming 'transform' is already defined in a previous cell)
# If not, you would define it here, e.g.,
# transform = transforms.Compose([
#     transforms.Resize((224, 224)),
#     transforms.ToTensor(),
#     transforms.Normalize([0.485, 0.456, 0.406],
#                          [0.229, 0.224, 0.225])
# ])


# Load datasets from the split directories
train_set = ImageFolder(data_dir / 'train', transform=transform)
val_set = ImageFolder(data_dir / 'val', transform=transform)

# Data loaders
train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
val_loader = DataLoader(val_set, batch_size=32, shuffle=False)

# Output dataset information
print("Classes:", train_set.classes)
print("Train size:", len(train_set))
print("Val size:", len(val_set))

import splitfolders
import os
import shutil

# --- Step 1: Extract the main zip file ---
zip_path = "/content/Alzimer.zip"
extracted_path = "/content/extracted_tumor"

# Create the extraction directory
if os.path.exists(extracted_path):
    shutil.rmtree(extracted_path)
os.makedirs(extracted_path)

print(f"Extracting {zip_path} to {extracted_path}")
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_path)

print("Contents after initial extraction:", os.listdir(extracted_path))

# --- Step 2: Find and clean the actual class folders ---
source_data_dir = os.path.join(extracted_path, "Combined Dataset", "train") # Correct path to actual class folders

cleaned_data_dir = "/content/cleaned_4_class_data" # Use a distinct directory for cleaned data

# Create the cleaned data directory
if os.path.exists(cleaned_data_dir):
    shutil.rmtree(cleaned_data_dir)
os.makedirs(cleaned_data_dir)

# List of actual class directories in your dataset
actual_class_directories = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']

if os.path.exists(source_data_dir):
    print(f"Found class directories in: {source_data_dir}")

    # Move only the actual class directories to the cleaned data directory
    for class_name in actual_class_directories:
        source_class_path = os.path.join(source_data_dir, class_name)
        destination_class_path = os.path.join(cleaned_data_dir, class_name)
        if os.path.exists(source_class_path) and os.path.isdir(source_class_path):
            shutil.copytree(source_class_path, destination_class_path) # Use copytree to move contents
            print(f"Copied {class_name} to {cleaned_data_dir}")
        else:
            print(f"Warning: Class directory {class_name} not found in {source_data_dir}")

    print("Contents of cleaned data directory:", os.listdir(cleaned_data_dir))

    # --- Step 3: Split the cleaned data ---
    input_folder_for_split = cleaned_data_dir # Split from the cleaned directory
    output_folder_split = "/content/brain_tumor_split"

    # Clear the output directory if it exists
    if os.path.exists(output_folder_split):
        shutil.rmtree(output_folder_split)

    print(f"\nSplitting data from {input_folder_for_split} to {output_folder_split}")
    splitfolders.ratio(input_folder_for_split, output=output_folder_split, seed=42, ratio=(.8, .2, 0))

    print("Created data splits in:", output_folder_split)
    print("Train split contents:", os.listdir(os.path.join(output_folder_split, 'train')))
    print("Validation split contents:", os.listdir(os.path.join(output_folder_split, 'val')))

    # Verification for the 4 classes
    all_found_in_train = True
    all_found_in_val = True
    for class_name in actual_class_directories:
        if not os.path.exists(os.path.join(output_folder_split, 'train', class_name)):
            all_found_in_train = False
        if not os.path.exists(os.path.join(output_folder_split, 'val', class_name)):
            all_found_in_val = False

    if all_found_in_train and all_found_in_val:
        print("✅ All expected class folders found in train and val directories.")
    else:
        print("❌ Some expected class folders NOT found as expected. Check the cleaning and splitting process.")

else:
    print(f"Error: Source data directory '{source_data_dir}' not found. Splitting cancelled.")

from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from pathlib import Path
import os

# Set the dataset directory to the output of splitfolders
data_dir = Path("/content/brain_tumor_split") # Corrected path to the split data

# Define transforms (assuming 'transform' is already defined in a previous cell)
# If not, you would define it here, e.g.,
# transform = transforms.Compose([
#     transforms.Resize((224, 224)),
#     transforms.ToTensor(),
#     transforms.Normalize([0.485, 0.456, 0.406],
#                          [0.229, 0.224, 0.225])
# ])


# Load datasets from the split directories
train_set = ImageFolder(data_dir / 'train', transform=transform)
val_set = ImageFolder(data_dir / 'val', transform=transform)

# Data loaders
train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
val_loader = DataLoader(val_set, batch_size=32, shuffle=False)

# Output dataset information
print("Classes:", train_set.classes)
print("Train size:", len(train_set))
print("Val size:", len(val_set))

import zipfile
import os
import shutil

# Define the path to the main zip file
zip_path = "/content/Alzimer.zip"
# Define the directory to extract the main zip file to
extracted_path = "/content/extracted_tumor"

# Create the extraction directory
if os.path.exists(extracted_path):
    shutil.rmtree(extracted_path)
os.makedirs(extracted_path)

# Extract the main zip file
print(f"Extracting {zip_path} to {extracted_path}")
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_path)

print("Contents after initial extraction:", os.listdir(extracted_path))

# The actual class folders ('Mild Impairment', etc.) are located within
# /content/extracted_tumor/Combined Dataset/train
# Let's set source_data_dir directly to this location.
source_data_dir = os.path.join(extracted_path, "Combined Dataset", "train")

# Define the directory to store the cleaned data (moving the 4 class folders here)
cleaned_data_dir = "/content/cleaned_4_class_data" # New, distinct directory to avoid conflicts

# Create the cleaned data directory
if os.path.exists(cleaned_data_dir):
    shutil.rmtree(cleaned_data_dir)
os.makedirs(cleaned_data_dir)

# List of actual class directories to move (based on the dataset structure)
actual_class_directories = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']

if os.path.exists(source_data_dir):
    print(f"Found class directories in: {source_data_dir}")

    # Move only the actual class directories to the cleaned data directory
    for class_name in actual_class_directories:
        source_class_path = os.path.join(source_data_dir, class_name)
        destination_class_path = os.path.join(cleaned_data_dir, class_name)
        if os.path.exists(source_class_path) and os.path.isdir(source_class_path):
            # Ensure destination parent directory exists
            os.makedirs(os.path.dirname(destination_class_path), exist_ok=True)
            shutil.move(source_class_path, cleaned_data_dir)
            print(f"Moved {class_name} to {cleaned_data_dir}")
        else:
            print(f"Warning: Class directory {class_name} not found in {source_data_dir}")

    print("Contents of cleaned data directory:", os.listdir(cleaned_data_dir))

else:
    print(f"Error: Source data directory '{source_data_dir}' not found. Please check extraction path and structure.")

import splitfolders
import os
import shutil

# Use the directory where the cleaned 'yes' and 'no' folders are located
input_folder_for_split = "/content/cleaned_4_class_data" # Corrected input directory
output_folder_split = "/content/sample_data/split_data"

# Clear the output directory if it exists
if os.path.exists(output_folder_split):
    shutil.rmtree(output_folder_split)

# Split into train (80%), val (20%), and test (0%)
if os.path.exists(input_folder_for_split) and any(os.path.isdir(os.path.join(input_folder_for_split, d)) for d in os.listdir(input_folder_for_split)):
    splitfolders.ratio(input_folder_for_split, output=output_folder_split, seed=42, ratio=(.8, .2, 0))

    print("Created data splits in:", output_folder_split)
    print("Train split contents:", os.listdir(os.path.join(output_folder_split, 'train')))
    print("Validation split contents:", os.listdir(os.path.join(output_folder_split, 'val')))
else:
    print(f"Error: Input folder '{input_folder_for_split}' not found or does not contain class directories. Please ensure the cleaning step was successful.")

from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from pathlib import Path
import os

# Set the dataset directory to the output of splitfolders
data_dir_split = Path('/content/sample_data/split_data') # Corrected path

# Print to confirm folder names (should be 'train' and 'val')
print("Folders inside split_data:", os.listdir(data_dir_split))

# Define transforms (assuming 'transform' is already defined in a previous cell)
# If not, you would define it here, e.g.,
# transform = transforms.Compose([
#     transforms.Resize((224, 224)),
#     transforms.ToTensor(),
#     transforms.Normalize([0.485, 0.456, 0.406],
#                          [0.229, 0.224, 0.225])
# ])


# Load datasets from the split directories
train_set = datasets.ImageFolder(data_dir_split / 'train', transform=transform)
val_set = datasets.ImageFolder(data_dir_split / 'val', transform=transform)

# Data loaders
train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
val_loader = DataLoader(val_set, batch_size=32, shuffle=False)

# Output dataset information
print("Classes:", train_set.classes)
print("Train size:", len(train_set))
print("Val size:", len(val_set))

import zipfile
import os
import shutil
import splitfolders

# --- Step 1: Extract the main zip file ---
zip_path = "/content/Alzimer.zip"
extracted_path = "/content/extracted_tumor"

# Create the extraction directory
if os.path.exists(extracted_path):
    shutil.rmtree(extracted_path)
os.makedirs(extracted_path)

print(f"Extracting {zip_path} to {extracted_path}")
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_path)

print("Contents after initial extraction:", os.listdir(extracted_path))

# --- Step 2: Find and clean the actual class folders ---
source_data_dir = os.path.join(extracted_path, "Combined Dataset", "train") # Correct path to actual class folders

cleaned_data_dir = "/content/cleaned_4_class_data" # Use a distinct directory for cleaned data

# Create the cleaned data directory
if os.path.exists(cleaned_data_dir):
    shutil.rmtree(cleaned_data_dir)
os.makedirs(cleaned_data_dir)

# List of actual class directories in your dataset
actual_class_directories = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']

if os.path.exists(source_data_dir):
    print(f"Found class directories in: {source_data_dir}")

    # Move only the actual class directories to the cleaned data directory
    for class_name in actual_class_directories:
        source_class_path = os.path.join(source_data_dir, class_name)
        destination_class_path = os.path.join(cleaned_data_dir, class_name)
        if os.path.exists(source_class_path) and os.path.isdir(source_class_path):
            shutil.copytree(source_class_path, destination_class_path) # Use copytree to move contents
            print(f"Copied {class_name} to {cleaned_data_dir}")
        else:
            print(f"Warning: Class directory {class_name} not found in {source_data_dir}")

    print("Contents of cleaned data directory:", os.listdir(cleaned_data_dir))

    # --- Step 3: Split the cleaned data ---
    input_folder_for_split = cleaned_data_dir # Split from the cleaned directory
    output_folder_split = "/content/brain_tumor_split"

    # Clear the output directory if it exists
    if os.path.exists(output_folder_split):
        shutil.rmtree(output_folder_split)

    print(f"\nSplitting data from {input_folder_for_split} to {output_folder_split}")
    splitfolders.ratio(input_folder_for_split, output=output_folder_split, seed=42, ratio=(.8, .2, 0))

    print("Created data splits in:", output_folder_split)
    print("Train split contents:", os.listdir(os.path.join(output_folder_split, 'train')))
    print("Validation split contents:", os.listdir(os.path.join(output_folder_split, 'val')))

    # Verification for the 4 classes
    all_found_in_train = True
    all_found_in_val = True
    for class_name in actual_class_directories:
        if not os.path.exists(os.path.join(output_folder_split, 'train', class_name)):
            all_found_in_train = False
        if not os.path.exists(os.path.join(output_folder_split, 'val', class_name)):
            all_found_in_val = False

    if all_found_in_train and all_found_in_val:
        print("✅ All expected class folders found in train and val directories.")
    else:
        print("❌ Some expected class folders NOT found as expected. Check the cleaning and splitting process.")

else:
    print(f"Error: Source data directory '{source_data_dir}' not found. Splitting cancelled.")

import os
import shutil

# Define the source directory containing the extracted folders
# This should be the directory where 'yes', 'no', and potentially 'brain_tumor_dataset' are located after extraction
# Based on previous output, the initial extraction seems to place 'yes' and 'no' directly in /content
source_dir_for_cleaning = "/content" # Corrected source directory

# Define a new directory to store the cleaned data (only 'yes' and 'no' folders)
cleaned_data_dir = "/content/sample_data/Combined Dataset"

# Create the cleaned data directory, clearing it if it already exists
if os.path.exists(cleaned_data_dir):
    shutil.rmtree(cleaned_data_dir)
os.makedirs(cleaned_data_dir)

# List the expected class directories
class_directories_to_keep = ['yes', 'no']

# Move only the class directories to the cleaned data directory
print(f"Cleaning data from {source_dir_for_cleaning} to {cleaned_data_dir}")
for class_name in class_directories_to_keep:
    source_path = os.path.join(source_dir_for_cleaning, class_name)
    destination_path = os.path.join(cleaned_data_dir, class_name)
    if os.path.exists(source_path) and os.path.isdir(source_path):
        # Use copytree to handle potential issues with moving across different file systems
        shutil.copytree(source_path, destination_path)
        print(f"Copied '{class_name}' to '{cleaned_data_dir}'")
    else:
        print(f"Warning: Class directory '{class_name}' not found in '{source_dir_for_cleaning}'.")

import splitfolders
import os
import shutil

# Use the directory where the cleaned class folders are located for splitting
# Based on previous successful cleaning (cell aKx5mUQl-fUo),
# the class folders are now in /content/cleaned_4_class_data
input_dir_for_split = "/content/cleaned_4_class_data"
output_dir_split = "/content/sample_data/split_data"

# Clear the output directory if it exists
if os.path.exists(output_dir_split):
    shutil.rmtree(output_dir_split)

# Ensure the cleaned input directory exists before splitting
actual_class_directories = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']

if os.path.exists(input_dir_for_split) and any(os.path.isdir(os.path.join(input_dir_for_split, d)) for d in os.listdir(input_dir_for_split)):
    print(f"Splitting data from {input_dir_for_split} to {output_dir_split}")
    splitfolders.ratio(
        input_dir_for_split, # Use the cleaned input directory
        output=output_dir_split,
        seed=42,
        ratio=(.8, .2, 0), # Split into train (80%), val (20%), test (0%)
        group_prefix=None
    )

    print("\nCreated data splits in:", output_dir_split)

    train_path = os.path.join(output_dir_split, 'train')
    val_path = os.path.join(output_dir_split, 'val')

    if os.path.exists(train_path):
        print("Train contents:", os.listdir(train_path))
    else:
        print("Train directory not created.")

    if os.path.exists(val_path):
        print("Val contents:", os.listdir(val_path))
    else:
        print("Val directory not created.")

    # Add checks to confirm class folders exist in the split
    all_found_in_train = True
    all_found_in_val = True
    for class_name in actual_class_directories:
        if not os.path.exists(os.path.join(train_path, class_name)):
            all_found_in_train = False
        if not os.path.exists(os.path.join(val_path, class_name)):
            all_found_in_val = False

    if all_found_in_train and all_found_in_val:
        print("✅ All expected class folders found in train and val directories as expected.")
    else:
        print("❌ Some expected class folders NOT found as expected. Check the cleaning and splitting process.")

else:
    print(f"Error: Cleaned input folder '{input_dir_for_split}' not found or does not contain class directories. Please ensure the cleaning step was successful.")

from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from pathlib import Path
import os

# Set the dataset directory to the output of splitfolders
data_dir_split = Path('/content/brain_tumor_split')

# Print to confirm folder names (should be 'train' and 'val')
print("Folders inside brain_tumor_split:", os.listdir(data_dir_split))

# Define transforms (assuming 'transform' is already defined in a previous cell)
# If not, you would define it here, e.g.,
# transform = transforms.Compose([
#     transforms.Resize((224, 224)),
#     transforms.ToTensor(),
#     transforms.Normalize([0.485, 0.456, 0.406],
#                          [0.229, 0.224, 0.225])
# ])


# Load datasets from the split directories
train_set = datasets.ImageFolder(data_dir_split / 'train', transform=transform)
val_set = datasets.ImageFolder(data_dir_split / 'val', transform=transform)

# Data loaders
train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
val_loader = DataLoader(val_set, batch_size=32, shuffle=False)

# Output dataset information
print("Classes:", train_set.classes)
print("Train size:", len(train_set))
print("Val size:", len(val_set))

import os
import shutil

# Define the source directory containing the extracted folders
# This should be the directory where 'yes', 'no', and potentially 'brain_tumor_dataset' are located after extraction
# Based on previous output, the initial extraction seems to place 'yes' and 'no' directly in /content
source_dir_for_cleaning = "/content/cleaned_4_class_data" # Corrected source directory to where class folders actually are

# Define a new directory to store the cleaned data (only 'yes' and 'no' folders)
cleaned_data_dir = "/content/sample_data/Combined Dataset"

# Create the cleaned data directory, clearing it if it already exists
if os.path.exists(cleaned_data_dir):
    shutil.rmtree(cleaned_data_dir)
os.makedirs(cleaned_data_dir)

# List the expected class directories (updated to actual class names)
class_directories_to_keep = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']

# Move only the class directories to the cleaned data directory
print(f"Cleaning data from {source_dir_for_cleaning} to {cleaned_data_dir}")
for class_name in class_directories_to_keep:
    source_path = os.path.join(source_dir_for_cleaning, class_name)
    destination_path = os.path.join(cleaned_data_dir, class_name)
    if os.path.exists(source_path) and os.path.isdir(source_path):
        # Use copytree to handle potential issues with moving across different file systems
        shutil.copytree(source_path, destination_path)
        print(f"Copied '{class_name}' to '{cleaned_data_dir}'")
    else:
        print(f"Warning: Class directory '{class_name}' not found in '{source_dir_for_cleaning}'.")

print("\nContents of cleaned data directory:", os.listdir(cleaned_data_dir))

import splitfolders
import os
import shutil

# Use the directory where the cleaned 'yes' and 'no' folders are located for splitting
input_dir_for_split = "/content/sample_data/Combined Dataset"
output_dir_split = "/content/sample_data/split_data"

# Clear the output directory if it exists
if os.path.exists(output_dir_split):
    shutil.rmtree(output_dir_split)

# Ensure the cleaned input directory exists before splitting
actual_class_directories = ['Mild Impairment', 'Moderate Impairment', 'No Impairment', 'Very Mild Impairment']

if os.path.exists(input_dir_for_split):
    print(f"Splitting data from {input_dir_for_split} to {output_dir_split}")
    splitfolders.ratio(
        input_dir_for_split, # Use the cleaned input directory
        output=output_dir_split,
        seed=42,
        ratio=(.8, .2, 0), # Split into train (80%), val (20%), test (0%)
        group_prefix=None
    )

    print("\nCreated data splits in:", output_dir_split)

    train_path = os.path.join(output_dir_split, 'train')
    val_path = os.path.join(output_dir_split, 'val')

    print("Train contents:", os.listdir(train_path) if os.path.exists(train_path) else "Train directory not created")
    print("Val contents:", os.listdir(val_path) if os.path.exists(val_path) else "Val directory not created")

    # Update verification to check for the actual four class folders
    all_found_in_train = True
    all_found_in_val = True
    for class_name in actual_class_directories:
        if not os.path.exists(os.path.join(train_path, class_name)):
            all_found_in_train = False
        if not os.path.exists(os.path.join(val_path, class_name)):
            all_found_in_val = False

    if all_found_in_train and all_found_in_val:
        print("✅ All expected class folders found in train and val directories as expected.")
    else:
        print("❌ Some expected class folders NOT found as expected. Check the cleaning and splitting process.")

else:
    print(f"Error: Cleaned input folder '{input_dir_for_split}' not found. Please ensure the cleaning step was successful.")

from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from pathlib import Path
import os

# Set the dataset directory to the output of splitfolders
data_dir = Path('/content/sample_data/split_data')

# Print to confirm folder names (will be 'train' and 'val' after splitting)
if os.path.exists(data_dir):
    print("Folders inside brain_tumor_split:", os.listdir(data_dir))
else:
    print("Error: brain_tumor_split directory not found.")


# Define transforms
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Load datasets from the split directories
# Add checks for train and val directories before loading
train_split_path = data_dir / 'train'
val_split_path = data_dir / 'val'

if os.path.exists(train_split_path) and os.path.exists(val_split_path):
    train_set = datasets.ImageFolder(train_split_path , transform=transform)
    val_set = datasets.ImageFolder(val_split_path, transform=transform)

    # Data loaders
    train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=32, shuffle=False)

    # Output
    print("Classes:", train_set.classes)
    print("Train size:", len(train_set))
    print("Val size:", len(val_set))
else:
    print("Error: Train or validation split directory not found. Please ensure splitting was successful.")

from google.colab import files

uploaded = files.upload()

!ls  # Shows current directory contents (usually /content/)

import torch
import torchvision.models as models

# Load a pretrained ResNet-50 model
resnet50_model = models.resnet50(pretrained=True)

# Calculate the total number of parameters
total_params = sum(p.numel() for p in resnet50_model.parameters())

# Print the total number of parameters
print(f"Total number of parameters in ResNet-50: {total_params}")

